### ISSUE TITLE
Enhancement request – Need for appropriate filters

### ISSUE THREAD

**Issue by Ricky-Tigg** [opennic/opennic-web#34]
Hi OpenNIC. As noticeable at [page]( https://servers.opennicproject.org/), on both tier 1 (Public authoritative servers) and tier 2 (Public DNS resolvers) tabs, listing of assumed non-anycast –since there is no mention about such property on the page– lack filtering regarding criteria  Anonymized logs, No logs kept, DNScrypt, Whitelisting, Blocklist. Such filters would be most appropriate for the selection of desired servers aimed to be used in configuration related to dnscrypt-proxy component.  Some of the resolvers may be wrongly informed, it is the case at least for [ns3.cz.dns.opennic.glue](https://servers.opennicproject.org/edit.php?srv=ns3.cz.dns.opennic.glue) which is informed as 'No logs kept' while obviously it is 'Anonymized logs'. Regards.

**Comment by JonahAragon** [comment]
This repo is only for [opennic.org](https://www.opennic.org), the homepage; we don't operate the servers listing at all (that's managed by @Shdwdrgn). As such I'm closing this issue.

I'll mention it to him on [IRC](https://www.opennic.org/irc/) but I'm not sure if he'll be able to add any more features at the moment. Sounds like it should be an API change anyways.

Also, the server you mentioned seems to not keep logs, so that listing appears accurate.

**Comment by Shdwdrgn** [comment]
I'm going to be pretty busy for the new few weeks so I can't promise any immediate updates to the page, but I can certainly see the value of additional filters for the server list.

In the meantime, are you familiar with the API page for looking up servers?  https://api.opennicproject.org/geoip/
Note that this page has a number of different filters available by modifying the URL, and most of them can be combined together.  You can see the full list at https://api.opennicproject.org/geoip/?help
