### ISSUE TITLE
Do you have an alternate url?

### ISSUE THREAD

**Issue by nixoz1** [opennic/opennic-web#69]
Hello, Do you have an alternate url?
The Iran government has blocked your main [url](https://www.opennic.org/), and I do not have access to your website!

**Comment by Fusl** [comment]
OpenNIC itself does not provide any alternative domains apart from all the main ones (opennic.org, opennicproject.org, opennicproject.net, opennicproject.com) which all seem to be blocked in Iran. You can try using the [Tor](https://www.torproject.org/) browser to work around that censorship, but my expectations that you'll be able to download that browser are very low since they surely have that blocked as well.
